server:
      port:8080




spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root
    password: Abc1234!
    driver-class-name: com.mysql.jdbc.Driver
#    mvc:
#    view:
#    prefix: /static/jsp/
#    suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean

  mapper:
    mappers: com.pinyu.miniprogram.mysql.mappers.BaseMapper
    identity: mysql
#  configuration:
#    map-underscore-to-camel-case=true





